name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Pobranie kodu
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Pythona
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Instalacja zależności
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Lint (flake8) i typowanie (mypy)
      - name: Lint with flake8
        run: flake8 .

      - name: Type-check with mypy
        run: mypy .

      # 5. Uruchomienie testów
      - name: Run pytest
        run: pytest --disable-warnings -q
